# Experiment setting for Deep Residual Learning for Image Recognition (He et al., 2015)

# Dataset
datasets:
  train:
    name: CIFAR10

# Optimizer
optimizer:
  SGD:
    weight_decay: 1e-4

# LR Scheduler
lr_scheduler:
  names:
  - MultiStepLR
  MultiStepLR:
    milestones: [91, 136]
    gamma: 0.1

# Training Loop
num_epochs: 182
